/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gomppermoritztontauben;

import java.awt.Graphics;

/**
 *
 * @author Moritz.Gompper
 */
public class Oberflaeche extends javax.swing.JPanel {
    
    private int xFK;
    private int yFK;
    private Steuerung s;

    /**
     * Creates new form Oberflaeche
     */
    
    
    public Oberflaeche() {
        s = new Steuerung(this);
        initComponents();
    }
    public void paintComponent(Graphics g){
        setFocusable(true);
        requestFocus();         
        super.paintComponent(g);
        s.zeichneObjekte(g);
        
    }
    public void geklicktMaus(){
        
    }
    

    
    public int gibXFK(){
        return xFK;
    }
    
    public int gibYFK(){
        return yFK;
    }
    
    public void zeigeBildFertig(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
